### ISSUE TITLE
Full Stack open 2020 contributors link returns 404

### ISSUE THREAD

**Issue by tarmojussila** [fullstack-hy2020/misc#9]
**Issue description**

The "Full Stack open 2020" contributors link returns 404 page not found response from GitHub.

**How to reproduce**

Step 1: Open link: https://github.com/fullstack-hy2020/misc/blob/master/contributors.md
Step 2: Try to open link: https://github.com/fullstackopen-2019/fullstackopen-hy2020.github.io/graphs/contributors
Step 3: Link (in step 2) returns 404 not found response from GitHub

**Additional info**

The link provided in step 1 is publicly visible at Full Stack Open website front page at: https://fullstackopen.com

**Comment by tarmojussila** [comment]
Pull request #4 or #5 should fix this issue. Both offer the same solution with a working link.

**Comment by mluukkai** [comment]
fixd
